language: python
python:
  - "2.7"
  - "3.6"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bzr git mercurial subversion tar
install:
  - pip install -r requirements.txt
  - mkdir bin
  - ln -s /usr/bin/true bin/obs-service-download_files # we don't test other services here
  - export PATH="$PWD/bin:$PATH"
script: PV=${TRAVIS_PYTHON_VERSION:0:1};echo $PV;make check$PV
