language: python
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq bzr git mercurial subversion tar
install:
  - pip install -r requirements.txt
  - mkdir bin
  - ln -s /usr/bin/true bin/obs-service-download_files # we don't test other services here
  - export PATH="$PWD/bin:$PATH"
  - if [[ ${TRAVIS_PYTHON_VERSION:0:3} == 2.7 ]]; then pip install flake8 pylint; fi
script: make check${TRAVIS_PYTHON_VERSION:0:1}
