# This is a basic workflow to help you get started with Actions

name: Testing
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.7', '3.8', '3.9', '3.10', '3.11']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: Install required dpkg packages
        run: sudo apt-get install libxslt1-dev bzr subversion mercurial

      - name: Generate default locales
        run: |
          sudo apt-get update && sudo apt-get install tzdata locales -y && sudo locale-gen "en_US.UTF-8"
          sudo dpkg-reconfigure locales
          sudo update-locale "LANG=en_US.UTF-8"
          sudo update-locale "LC_ALL=en_US.UTF-8"
          locale

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python dependencies
        run: pip install -r requirements.txt

      - name: Lint with flake8
        run: make flake8

      - name: Lint code with pylint
        run: make pylint

      - name: Lint test with pylint
        run: make pylinttest

      - name: Run tests
        run: |
          locale
          make test
